// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.shim.finance' | (string & {});
};

export type Institution = {
    id: string;
    institutionId: string | null;
    institutionName: string | null;
    status: 'healthy' | 'error';
    lastSyncedAt: DateTimeUtc | null;
    createdAt: DateTimeUtc;
};

/**
 * a string to be decoded into a DateTime.Utc
 */
export type DateTimeUtc = string;

/**
 * The request did not match the expected schema
 */
export type HttpApiDecodeError = {
    issues: Array<Issue>;
    message: string;
    _tag: 'HttpApiDecodeError';
};

/**
 * Represents an error encountered while parsing a value to match the schema
 */
export type Issue = {
    /**
     * The tag identifying the type of parse issue
     */
    _tag: 'Pointer' | 'Unexpected' | 'Missing' | 'Composite' | 'Refinement' | 'Transformation' | 'Type' | 'Forbidden';
    /**
     * The path to the property where the issue occurred
     */
    path: Array<PropertyKey>;
    /**
     * A descriptive message explaining the issue
     */
    message: string;
};

export type PropertyKey = string | number | {
    _tag: 'symbol';
    key: string;
};

export type Unauthorized = {
    message: string;
    _tag: 'Unauthorized';
};

export type InternalError = {
    message: string;
    _tag: 'InternalError';
};

export type InstitutionsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/institutions';
};

export type InstitutionsListErrors = {
    /**
     * The request did not match the expected schema
     */
    400: HttpApiDecodeError;
    /**
     * Unauthorized
     */
    401: Unauthorized;
    /**
     * InternalError
     */
    500: InternalError;
};

export type InstitutionsListError = InstitutionsListErrors[keyof InstitutionsListErrors];

export type InstitutionsListResponses = {
    /**
     * Success
     */
    200: Array<Institution>;
};

export type InstitutionsListResponse = InstitutionsListResponses[keyof InstitutionsListResponses];
